citasyconsultas/urls.py
from .ajax import load_Municipio, load_Horario

from django.urls import path, include
from .views import *

app_name = 'citasyconsultas'
urlpatterns=[
	path('index/', index, name='index'),
	#views para medicamento
	path('gestionMedicamento/', ListadoMedicamento.as_view(), name='listado_medicamento'),
	path('crearMedicamento/', crearMedicamento.as_view(), name='crear_medicamento'),
	path('modificarMedicamento/<int:pk>/', modificarMedicamento.as_view(), name='modificar_medicamento'),
	path('eliminarMedicamento/<int:pk>/', eliminarMedicamento.as_view(), name='eliminar_medicamento'),

	# URL's y VIEWS para el control de las citas
	path('nueva_cita/', CrearCita.as_view(), name = 'nueva_cita'),
	path('gestion_cita/', GestionCitas.as_view(), name = 'gestion_cita'),
	path('modificar_cita/<int:pk>/', ModificarCita.as_view(), name = 'modificar_cita'),
	path('cancelar_cita/<int:pk>/', CancelarCita.as_view(), name = 'cancelar_cita'),
	path('confirmar_cancelar/', ConfirmarCancelar, name = 'confirmar_cancelar'),
	path('cobrar/', RealizarCobro, name = 'cobrar'),
	path('citasParaHoy/', citasParaHoy, name='citasParaHoy'),
	
	path('verCita/<int:pk>/', verCita.as_view(), name='verCita'),



	#views para servicio
	path('gestionServicio/', ListadoServicio.as_view(), name='listado_servicio'),
	path('crearServicio/', crearServicio.as_view(), name='crear_servicio'),
	path('modificarServicio/<int:pk>/', modificarServicio.as_view(), name='modificar_servicio'),
	path('eliminarServicio/<int:pk>/', eliminarServicio.as_view(), name='eliminar_servicio'),

	#views para exp
	path('gestionExpediente/', GestionExpediente.as_view(), name='listado_expediente'),
	path('crearExpediente/', crearExpediente.as_view(), name='crear_expediente'),
	path('modificarExpediente/<int:pk>/', modificarExpediente.as_view(), name='modificar_expediente'),

# R ====================================================================================================
    path('ver_expediente/(?P<pk>[0-9]+)/$', DetalleExpediente, name='ver_expediente'),
	path('buscar_exp/', BuscarExpediente, name = 'buscar_exp'),
	# CONSULTAS AJAX PARA EXPEDIENTE Y CITA    =======================
	path('ajax/load_Municipio/', load_Municipio, name='load_Municipio'),
	path('ajax/load_Horario/', load_Horario, name='load_Horario'),
# ======================================================================================================

	#views para consulta
	path('consultasPendientes/', consultasPendientes, name='listado_consulta'),
	path('modificarConsulta/<int:pk>/', modificarConsulta.as_view(), name='modificar_consulta'),
	path('crearConsulta', crearConsulta.as_view(), name='crear_consulta'),

    # VIEWS PARA  CONTROL DE USUARIOS
	path('iniciarSesion', iniciarSesion, name='inicar_sesion'),
	path('autenticarUsuario', autenticarUsuario, name='autenticar_usuario'),
	path('cerrarSesion', cerrarSesion, name='cerrar_sesion'),

	#
	path('gestionMedicamento', ir_a_medicamento, name='ir_a_medicamento'),
	path('gestionServicio', ir_a_servicio, name='ir_a_servicio'),

]

proyectohdp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('citasyconsultas/', include('citasyconsultas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
 

]

templates/base/base.html
{% load static %}
<!doctype html>
<html>
<head>

	
        <meta charset="utf-8"/>
        <meta name="description" content=""/>
        <meta name="author" content=""/>



        <title>{% block title %}Expediente Clinico{% endblock %}</title>

        <link rel="stylesheet" href="../../static/css/bootstrap.min.css">
        <link rel="stylesheet" href="../../static/css/bootstrap.css">


      <script type="text/javascript" src="../../static/js/jquery-2.1.1.js"></script>
        <script type="text/javascript" src="../../static/js/bootstrap.min.js"></script>
       

        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.min.css'  %}"/>
        <script type="text/javascript" src="{% static 'js/jquery.js' %}" charset="UTF-8"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" charset="UTF-8"></script>
        <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
            {% block head %}{% endblock %}
    

  
</head>



<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Expediente Clinico</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"> <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
    </ul>
    <form action="{% url 'citasyconsultas:cerrar_sesion'%}" method="post">
   {% csrf_token %}      
        
                  
                    <input type = "submit" class = "btn btn-succes btn-lg text-white" value= "cerrar sesion" style ="margin-top:20px;background-color:green;margin-bottom:60px;">
                </form>
                
            </div>
        </div>
    </form>
  </div>
</nav>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
              
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>

  
</body>
</html>