citasyconsultas/urls.py
from .ajax import load_Municipio, load_Horario

from django.urls import path, include
from .views import *

app_name = 'citasyconsultas'
urlpatterns=[
	path('index/', index, name='index'),
	#views para medicamento
	path('gestionMedicamento/', ListadoMedicamento.as_view(), name='listado_medicamento'),
	path('crearMedicamento/', crearMedicamento.as_view(), name='crear_medicamento'),
	path('modificarMedicamento/<int:pk>/', modificarMedicamento.as_view(), name='modificar_medicamento'),
	path('eliminarMedicamento/<int:pk>/', eliminarMedicamento.as_view(), name='eliminar_medicamento'),

	# URL's y VIEWS para el control de las citas
	path('nueva_cita/', CrearCita.as_view(), name = 'nueva_cita'),
	path('gestion_cita/', GestionCitas.as_view(), name = 'gestion_cita'),
	path('modificar_cita/<int:pk>/', ModificarCita.as_view(), name = 'modificar_cita'),
	path('cancelar_cita/<int:pk>/', CancelarCita.as_view(), name = 'cancelar_cita'),
	path('confirmar_cancelar/', ConfirmarCancelar, name = 'confirmar_cancelar'),
	path('cobrar/', RealizarCobro, name = 'cobrar'),
	path('citasParaHoy/', citasParaHoy, name='citasParaHoy'),
	
	path('verCita/<int:pk>/', verCita.as_view(), name='verCita'),



	#views para servicio
	path('gestionServicio/', ListadoServicio.as_view(), name='listado_servicio'),
	path('crearServicio/', crearServicio.as_view(), name='crear_servicio'),
	path('modificarServicio/<int:pk>/', modificarServicio.as_view(), name='modificar_servicio'),
	path('eliminarServicio/<int:pk>/', eliminarServicio.as_view(), name='eliminar_servicio'),

	#views para exp
	path('gestionExpediente/', GestionExpediente.as_view(), name='listado_expediente'),
	path('crearExpediente/', crearExpediente.as_view(), name='crear_expediente'),
	path('modificarExpediente/<int:pk>/', modificarExpediente.as_view(), name='modificar_expediente'),

# R ====================================================================================================
    path('ver_expediente/(?P<pk>[0-9]+)/$', DetalleExpediente, name='ver_expediente'),
	path('buscar_exp/', BuscarExpediente, name = 'buscar_exp'),
	# CONSULTAS AJAX PARA EXPEDIENTE Y CITA    =======================
	path('ajax/load_Municipio/', load_Municipio, name='load_Municipio'),
	path('ajax/load_Horario/', load_Horario, name='load_Horario'),
# ======================================================================================================

	#views para consulta
	path('consultasPendientes/', consultasPendientes, name='listado_consulta'),
	path('modificarConsulta/<int:pk>/', modificarConsulta.as_view(), name='modificar_consulta'),
	path('crearConsulta', crearConsulta.as_view(), name='crear_consulta'),

    # VIEWS PARA  CONTROL DE USUARIOS
	path('iniciarSesion', iniciarSesion, name='inicar_sesion'),
	path('autenticarUsuario', autenticarUsuario, name='autenticar_usuario'),
	path('cerrarSesion', cerrarSesion, name='cerrar_sesion'),

	#
	path('gestionMedicamento', ir_a_medicamento, name='ir_a_medicamento'),
	path('gestionServicio', ir_a_servicio, name='ir_a_servicio'),

]

proyectohdp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('citasyconsultas/', include('citasyconsultas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
 

]

citasyconsultas/models.py
from .validators import valid_Nombres, valid_Apellidos, valid_Telefono
from django.core.exceptions import ValidationError

from django.db import models
from datetime import *
from django.utils import timezone



class Horario(models.Model):
	hora = models.CharField(max_length = 10)

	def __str__(self):
		return self.hora

# Modelo de los Servicios
class Servicio (models.Model):

	codSer = models.IntegerField(primary_key = True)
	nomSer = models.CharField(max_length = 200) # Nombre del servicio
	precio = models.DecimalField(max_digits = 10, decimal_places = 2)
	duraci = models.CharField(max_length = 10)# Duracion PROMEDIO del servicio en minutos

	def __str__(self):
		return self.nomSer
	
	class Meta:
		ordering = ('nomSer',)

class Departamento(models.Model):
	numDep = models.IntegerField(primary_key = True) 
	nomDep = models.CharField(max_length = 100, help_text = "Ingrese un departamento")
	def __str__(self):
		return self.nomDep

	class Meta:
		ordering = ('nomDep',)

class Municipio(models.Model):
	numMunicipio = models.IntegerField(primary_key = True)
	nomMunicipio = models.CharField(max_length = 100, help_text = "Ingrese un municipio")
	departamento = models.ForeignKey(Departamento, on_delete = models.CASCADE)
	def __str__(self):
		return self.nomMunicipio	

	class Meta:
		ordering = ('nomMunicipio',)

class Paciente(models.Model):
	numExpediente = models.IntegerField(primary_key = True)
	nomPaciente = models.CharField(max_length = 200, help_text = "Ingrese el nombre del paciente", validators = [valid_Nombres])
	apelPaciente = models.CharField(max_length = 200, help_text = "Ingrese el apellido del paciente", validators = [valid_Apellidos])
	fechaNacimiento = models.DateField(null=True, blank=True)
	emailPaciente = models.CharField(max_length = 200, help_text = "Ingrese eMail del paciente")
	depResidencia = models.ForeignKey(Departamento, on_delete=models.PROTECT, default = '10')
	munResidencia = models.ForeignKey(Municipio, on_delete = models.PROTECT, default = '15')
	telefono = models.CharField(max_length = 8, help_text = "Solo numeros", validators=[valid_Telefono])
	def __str__(self):
		return self.apelPaciente + ", " + self.nomPaciente

	class  Meta:
		unique_together = ['telefono',]


# Modelo de laas citas.
class Cita (models.Model):
	numCit = models.IntegerField(primary_key = True, help_text = "Numero de cita del dia", error_messages={'unique':"Ya existe una Cita con este numero"})# Numero de cita del dia
	pacien = models.ForeignKey('Paciente', on_delete = models.PROTECT, null=True)
	fecCon = models.DateField(null=True, verbose_name="Fecha de Cita")# Fecha de la consulta
	horCon = models.ForeignKey(Horario, null=True, on_delete=models.PROTECT, verbose_name="Hora de Cita")
	servic = models.ForeignKey(Servicio,on_delete = models.PROTECT, null=True)
	estado = models.IntegerField(default=0, null=True, help_text = "Activa (0), Completada (1)") #  Pendiente = 0 ,  Completado = 1
	fecCre = models.DateField(auto_now_add = True)# fecha de creacion
	
	def __str__(self):
		return self.numCit

	class Meta:
		ordering = ('numCit',)
		unique_together =['fecCon', 'horCon']
    

	def unique_error_message(self, model_class, unique_check):
		if len(unique_check) != 1:
			return 'Esta hora en esta fecha ya esta ocupada, seleccione otra hora y/o fecha'

# Create your models here.
class Medicamento(models.Model):
	codMedicamento=models.IntegerField(help_text="Ingrese el codigo del Medicamento",primary_key = True)
	nomMedicamento=models.CharField(max_length=200,help_text="Ingrese el nombre del Medicamento")
	def __str__(self):
		return self.nomMedicamento

class Medico(models.Model):
	codMedico=models.IntegerField(help_text="Ingrese el codigo del Medico",primary_key = True)
	nomMedico=models.CharField(max_length=200,help_text="Ingrese el nombre del Medico")
	usuario=models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
	def __str__(self):
		return self.nomMedico

class Secretaria(models.Model):
	codSec=models.IntegerField(help_text="Ingrese el codigo de la Secretaria",primary_key = True)
	nomSec=models.CharField(max_length=200,help_text="Ingrese el nombre de la Secretaria")
	usuario=models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
	def __str__(self):
		return self.nomSec

class Usuario(models.Model):
	codUsu=models.CharField(max_length=10,help_text="Ingrese el Usuario, maximo 10 caracteres",primary_key = True)
	pasUsu=models.CharField(max_length=20,help_text="Ingrese contraseña, maximo 20 caracteres")

	TIPO_USUARIO= (
		('s','Secretaria'),
		('m', 'Medico'),		
		)

	tipo_usuario= models.CharField(
        max_length=1,
        choices=TIPO_USUARIO,
        blank=True,
        default='s',
        help_text='Tipo de usuario en el sistema')

	def __str__(self):
		 return '{0}, {1},{2}'.format(self.codUsu, self.pasUsu, self.tipo_usuario)


class Consulta(models.Model):
	codCon=models.IntegerField(primary_key = True)
	diagnostico=models.CharField(max_length=500,help_text="Ingrese el diagnostico", null=True, blank=True)	
	dosis=models.CharField(max_length=500,help_text="Ingrese la dosis", null=True, blank=True)
	paciente = models.ForeignKey('Paciente', help_text="Seleccione el paciente",on_delete=models.SET_NULL, null=True)
	#medico=models.ForeignKey('Medico', on_delete=models.SET_NULL, null=True)
	fecConHoy=models.DateField(default=datetime.now().date())
	medicamentos=models.ManyToManyField(Medicamento, null=True, blank=True)
	servicios=models.ForeignKey('Servicio', blank=True, on_delete=models.SET_NULL, null=True)
	
	Estado_Consulta= (
		('f','Finalizada'),
		('p', 'Pendiente'),		
		)

	estado= models.CharField(
        max_length=1,
        choices=Estado_Consulta,
        blank=True,
        default='p')


	def __str__(self):
		return self.dosis

citasyconsultas/views.py
from django.db.models import Q
from django import forms
from django.template import loader


from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.urls import reverse_lazy, reverse

from datetime import *
from .models import *
from .forms import *
from django.views.generic.detail import DetailView
from django.views import View

from django.http import HttpResponseRedirect, HttpResponse
from django.core import serializers

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login

def index(request):   

    return render(
        request,
        'base/base.html',
        context={},
    )
# CITA Y SU CRUD==============================================================
class CrearCita(CreateView):
    template_name = 'citasyconsultas/cita_form.html'
    form_class = NuevaCitaForm
    success_url = reverse_lazy('citasyconsultas:gestion_cita')


class GestionCitas(ListView):
	model = Cita
	template_name = 'citasyconsultas/gestionCitas.html'
	context_object_name = 'citas'


class ModificarCita(UpdateView):
    template_name = 'citasyconsultas/modificarCita.html'
    model = Cita
    form_class = ModificarCitaForm
    success_url = reverse_lazy('citasyconsultas:gestion_cita')
    

class CancelarCita(DeleteView):
    template_name = 'citasyconsultas/cancelarCita.html'
    model = Cita
    success_url = reverse_lazy('citasyconsultas:gestion_cita')

def citasParaHoy(request):
    fechahoy=datetime.now().date()
    citas=Cita.objects.filter(fecCon__contains=fechahoy)            
    return render(request, 'citasyconsultas/citasParaHoy.html',context={'citas':citas})

class verCita(DetailView):
    template_name = 'citasyconsultas/verCita.html'
    model = Cita
   ## context_object_name = 'verCita'
    ##success_url = reverse_lazy('citasyconsultas:gestion_cita')


#==========================================================================
#REALIZAR COBRO============================================================
def RealizarCobro(request):
    query = request.GET.get('q')
    hoy = datetime.now().date()
    qset = (Q(numCit = query) & Q(fecCon__contains = hoy))
    results = Cita.objects.filter(qset)

    return render(request, 'citasyconsultas/cobro.html',context={'cita_a_cobrar':results})
          
#==========================================================================
# CONFIRMACION DE CANCELACION DE CITA======================================
def ConfirmarCancelar(request):
    return render(request, 'citasyconsultas/confirmCancel.html')
          
#==========================================================================
# BUSCAR UN EXPEDIENTE ESPECIFICO==========================================
def BuscarExpediente(request):
    queryNom = request.GET.get('expNom')
    queryApe = request.GET.get('expApe')
    qset = (Q(nomPaciente__icontains = queryNom) & Q(apelPaciente__icontains = queryApe))
    results = Paciente.objects.filter(qset)
    
    return render(request, 'citasyconsultas/buscarExp.html',context={'exp':results})
#==========================================================================

#modelos de Medicamento
class ListadoMedicamento(ListView):
    model = Medicamento
    template_name = 'citasyconsultas/gestionMedicamento.html'
    context_object_name = 'medicamentos'

class crearMedicamento(CreateView):
    template_name = 'citasyconsultas/crearMedicamento.html'
    form_class = MedicamentoForm
    success_url = reverse_lazy('citasyconsultas:listado_medicamento')

class modificarMedicamento(UpdateView):
    model = Medicamento
    template_name = 'citasyconsultas/crearMedicamento.html'
    form_class = MedicamentoForm
    success_url = reverse_lazy('citasyconsultas:listado_medicamento')

class eliminarMedicamento(DeleteView):
    model = Medicamento
    template_name='citasyconsultas/eliminarMedicamento.html'
    success_url = reverse_lazy('citasyconsultas:listado_medicamento')

#modelos de Servicio
class ListadoServicio(ListView):
    model = Servicio
    template_name = 'citasyconsultas/gestionServicio.html'
    context_object_name = 'servicios'

class crearServicio(CreateView):
    template_name = 'citasyconsultas/crearServicio.html'
    form_class = ServicioForm
    success_url = reverse_lazy('citasyconsultas:listado_servicio')

class modificarServicio(UpdateView):
    model = Servicio
    template_name = 'citasyconsultas/crearServicio.html'
    form_class = ModificarServicioForm
    success_url = reverse_lazy('citasyconsultas:listado_servicio')

class eliminarServicio(DeleteView):
    model = Servicio
    template_name='citasyconsultas/eliminarServicio.html'
    success_url = reverse_lazy('citasyconsultas:listado_servicio')




class GestionExpediente(ListView):
    model = Paciente
    template_name = 'citasyconsultas/gestionExpediente.html'
    context_object_name = 'expedientes'

class crearExpediente(CreateView):
    template_name = 'citasyconsultas/crearExpediente.html'
    form_class = ExpedienteForm
    success_url = reverse_lazy('citasyconsultas:listado_expediente')

class modificarExpediente(UpdateView):
    model = Paciente
    template_name = 'citasyconsultas/crearExpediente.html'
    form_class = ModificarExpedienteForm
    success_url = reverse_lazy('citasyconsultas:listado_expediente')
# TENTATIVAMENTE SE ELIMINARA =====================================================================
class VerExpediente(DetailView):
    template_name = 'citasyconsultas/verExpediente.html'
    model = Paciente
# =================================================================================================

def consultasPendientes(request):
    fechahoy=datetime.now().date()
    consultas=Consulta.objects.filter(estado='p').filter(fecConHoy__contains=fechahoy)            
    return render(request, 'citasyconsultas/consultasPendientes.html',context={'consultas':consultas})

class modificarConsulta(UpdateView):
    model = Consulta
    template_name = 'citasyconsultas/modificarConsulta.html'
    form_class = ConsultaForm
    success_url = reverse_lazy('citasyconsultas:listado_consulta')

class crearConsulta(CreateView):   
    template_name = "citasyconsultas/crearConsulta.html"
    form_class = nuevaConsultaForm
    success_url = reverse_lazy('citasyconsultas:gestion_cita')


   
def iniciarSesion(request):   

    return render(
        request,
        'citasyconsultas/login.html'
    )

def autenticarUsuario(request):
    
        username = request.POST.get('username')
        password = request.POST.get('password')
        filtro = Usuario.objects.filter(codUsu=username).filter(pasUsu=password).values('tipo_usuario')
        if filtro:
            if filtro[0].get('tipo_usuario')=='m':           
                return redirect('citasyconsultas:listado_consulta')            
            else:
                if filtro[0].get('tipo_usuario')=='s': 
                    return redirect('citasyconsultas:gestion_cita')
        else:   
            return render(request,'citasyconsultas/errorUsuario.html')
                
                
        
def cerrarSesion(request):
    return render(request,'citasyconsultas/login.html')


def ir_a_medicamento(request):
    return redirect('citasyconsultas:listado_medicamento')

def ir_a_servicio(request):
    return redirect('citasyconsultas:listado_servicio')

# PARA VER EXPEDIENTE Y CONSULTAS ===============================================================
def DetalleExpediente(request, pk):
    expediente =Paciente.objects.get(numExpediente = pk)
    consultas = Consulta.objects.filter(paciente = pk).filter(estado='f')
    return render(request, 'citasyconsultas/verExpediente.html', context = {'expediente':expediente,'consultas':consultas})
# ===============================================================================================

        

templates/citasyconsultas/cita_form.html
{% extends 'base/base.html'%}

{% block title %} Crear de Citas {% endblock %}

{% block encabezado %} Crear de Citas {% endblock %}
{% block content %}
<div >
        <div class="modal-content">
        
        <form role="form" action="{% url 'citasyconsultas:nueva_cita' %}" method="post">
       
            <div class="modal-body">
                {% csrf_token %}
    
                <div class="panel-body">
                    {{ form.as_p }}
                </div>
            </div>
                                        
            <div class="modal-footer">
                <div class="col-lg-12 text-right">
                    <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" name="submit" value="Guardar">

                    <button type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" style="background-color:#f6685e;color:white" onclick="return abrir_modal('{% url 'citasyconsultas:confirmar_cancelar' %}', 'Confirmar Cancelacion')">Cancelar</button>
                </div>
                </div>
            </form>
        </div>
</div>

</div>
<div id="popup">

</div>
<script>
var modal;

//  SELECT DEPENDIENTE PARA LA HORA DE LA CITA ============

$(document).ready(function(){
        $("#id_fecCon").on("change", getHorarios);    
    });

    function getHorarios(){
        var fechaCita = $("#id_fecCon").val();
        if (fechaCita){
            $("#id_horCon").html("");
            var request = $.ajax({
                type: "GET",
                url: "{% url 'citasyconsultas:load_Horario' %}",
                data: {
                    "fecha":fechaCita
                },
            });
            request.done(function(response){
                $("#id_horCon").html(response);
               
            });
    
        }else{
            $("#id_horCon").html('<option value="" selected = "selected">-------</option>');      
            $("#id_horCon").trigger("change");
        }
    }

// ========================================================

//<!--Para el  datepicker-->
$(function(){
	$(".datepicker").datepicker({
		monthNames: [ "Enero","Ferero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Dicimbre" ],
		monthNamesShort: [ "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" ], 
		dayNames: [ "Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" ], 
		dayNamesShort: [ "Dom", "Lun", "Mar", "Mie", "jue", "Vie", "Sab" ], 
		dayNamesMin: [ "Dom", "Lun", "Mar", "Mie", "jue", "Vie", "Sab"],
		dateFormat: "yy-mm-dd",
		changeYear: true,
		changeMonth: true,
		yearRange: "2019:3000",
	});
});


var modal;

function abrir_modal(url, titulo)
{
    modal = $('#popup').dialog(
    {
        title: titulo,
        modal: true,
        width: 600,
        resizable: false
    }).dialog('open').load(url)
}

function cerrar_modal()
{
    modal.dialog("close");
}

$(document).ready(function()
{
    var table = $('#tabla').dataTable( {
        "language": {
                url: "/static/localizacion/es_ES.json"
        }
    } );
});


</script>
{% endblock %}

templates/citasyconsultas/crearConsulta.html
<div >
        <div class="modal-content">  
        <form role="form" action="{% url 'citasyconsultas:crear_consulta'%}" method="post">
        
     	 <div class="modal-body">
                                {% csrf_token %}
    
                                        <div class="panel-body">
                            
                                                {{ form.as_p }}
                                        </div>
                                </div>
                                        
                        <div class="modal-footer">
                                <div class="col-lg-12 text-right">
                                       <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" name="submit" value="Guardar">
                                        <button type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" style="background-color:#f6685e;color:white" onclick="return cerrar_modal()">
                                                Cancelar
                                        </button>
                                </div>
                        </div>
                </form>
        </div>
</div>

templates/citasyconsultas/crearExpediente.html
{% extends 'base/base.html'%}

{% block title %} Gestion de Expedientes {% endblock %}

{% block encabezado %} Gestion de Paciente {% endblock %}
{% block content %}

<div >
        <div class="modal-content">
        {% if object %}
        <form id="expForm" action="{% url 'citasyconsultas:modificar_expediente' object.pk %}" method="post">
        {% else %}
        <form id="expForm" id="ExpedienteForm" action="{% url 'citasyconsultas:crear_expediente' %}" method="post" >
        {% endif %}
            <div class="modal-body">
                                {% csrf_token %}
    
                                        <div class="panel-body">
                                                {{ form.as_p }}
                                        </div>
                                </div>
                                        
                        <div class="modal-footer">
                                <div class="col-lg-12 text-right">
                                       <input type="submit" class="btn-success" name="submit" value="Guardar" 
                                       style="color:white; background-color: #33CC00">
                                       
                                       <a href="{% url 'citasyconsultas:listado_expediente' %}" class="btn btn-success" style="color:white; background-color:#f6685e">Cancelar</a>

                                </div>
                        </div>
                </form>
        </div>
</div>

<script type="text/javascript">

// SELECT DEPENDIENTE PARA LOS MUNICIPIOS====================================
    $(document).ready(function(){
        $("#id_depResidencia").on("change", getMunicipios);    
    });

    function getMunicipios(){
        var departamentoId = $("#id_depResidencia").val();
        if (departamentoId){
            $("#id_munResidencia").html("");
            var request = $.ajax({
                type: "GET",
                url: "{% url 'citasyconsultas:load_Municipio' %}",
                data: {
                    "depId":departamentoId
                },
            });
            request.done(function(response){
                $("#id_munResidencia").html(response);
               
            });
    
        }else{
            $("#id_munResidencia").html('<option value="" selected = "selected">-----------</option>');      
            $("#id_munResidencia").trigger("change");
        }
    }
//===========================================================================

//<!--Para el  datepicker-->
    $(function(){
        $(".datepicker").datepicker({
            monthNames: [ "Enero","Ferero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Dicimbre" ],
            monthNamesShort: [ "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" ], 
            dayNames: [ "Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" ], 
            dayNamesShort: [ "Dom", "Lun", "Mar", "Mie", "jue", "Vie", "Sab" ], 
            dayNamesMin: [ "Dom", "Lun", "Mar", "Mie", "jue", "Vie", "Sab"],
            dateFormat: "yy-mm-dd",
            changeYear: true,
            changeMonth: true,
            yearRange: "1900:3000",
        });
    });

</script>
{%endblock%}

templates/citasyconsultas/gestionCitas.html
{% extends 'base/base.html'%}

{% block title %} Gestion de Citas {% endblock %}

{% block encabezado %} Gestion de Citas {% endblock %}
{% block content %}
<h3>Citas</h3>
<div class="container">
	<div class="row">
	<a href="{% url 'citasyconsultas:nueva_cita' %}" class="btn btn-success" style="color:white; background-color:#33CC00">Nueva Cita</a>.

	<a href="{% url 'citasyconsultas:cobrar' %}" class="btn btn-success" style="color:white; background-color:#33CC00">Realizar Cobro</a>.

<!-- PARA MIENTRAS PONGO ESTE BOTON AQUI-->
	<a href="{% url 'citasyconsultas:citasParaHoy' %}" class="btn btn-success" style="color:white; background-color:#33CC00">Citas para Hoy</a>.
	<div><a href="{% url 'citasyconsultas:listado_expediente' %}" class="btn btn-success" style="color:white; background-color:#f6685e">Expedientes</a></div>.
	
	<a href="{% url 'citasyconsultas:buscar_exp' %}" class="btn btn-success" style="color:white; background-color:#33CC00">Buscar Expediente</a></a> 
	<div><br>
	<a onclick="return abrir_modal('{% url 'citasyconsultas:crear_consulta' %}', 'Crear consulta al paciente')" class="btn btn-success" style="color:white; background-color:#33CC00" value="Crear consulta">Crear Consulta</a>
    </div>

</div>
<br>
<div class="row text-center">
	<table  class="table table- stripped">
		<tr style="text-align: center">
			<th style="text-align: center">Numero de Cita</th>
			<th style="text-align: center">Fecha de Cita</th>
			<th style="text-align: center">Paciente</th>
            <th style="text-align: center">Hora</th>
            <th style="text-align: center">Razon de Consulta</th>
            <th style="text-align: center">Fecha de Creacion</th>
          
            

		</tr>
		{% for cit in citas %}
					<tr>
						<td>{{cit.numCit}}</td>
						<td>{{cit.fecCon}}</td>
						<td>{{cit.pacien}}</td>
						<td>{{cit.horCon}}</td>
						<td>{{cit.servic}}</td>
						<td>{{cit.fecCre}}</td>
						
						
						<td style="text-align:center;">
							<a href="#" onclick="return abrir_modal('{% url 'citasyconsultas:modificar_cita' cit.pk %}', 'Modificar Cita Numero: -->> {{ cit.numCit }}')" class="btn"><span class="glyphicon glyphicon-pencil">Editar</a>
						</td>

						<td style="text-align:center;">
							<a href="#" onclick="return abrir_modal('{% url 'citasyconsultas:cancelar_cita' cit.pk %}', 'Emiminar Cita numero {{ cit.numCit}}')" class="btn"><span class="glyphicon glyphicon-trash"></span>Cancelar</a>
						</td>

					
					</tr>
		{% endfor %}
	</table>
</div>
</div>
<div id="popup">

</div>
<script>
var modal;

function abrir_modal(url, titulo)
{
    modal = $('#popup').dialog(
    {
        title: titulo,
        modal: true,
        width: 600,
        resizable: false
    }).dialog('open').load(url)
}

function cerrar_modal()
{
    modal.dialog("close");
}

$(document).ready(function()
{
    var table = $('#tabla').dataTable( {
        "language": {
                url: "/static/localizacion/es_ES.json"
        }
    } );
});


</script>


{% endblock %}